name: Dev CICD workflow

on:
  push:
    branches:
      - main

jobs:
  Scan:
    name: Scan 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout 
    - name: Scan 
      run: echo "TODO"
  Build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker build 
      run: |
        docker build -t zeabix/${{ github.event.repository.name }}:${{ github.sha }} --build-arg appname=${{ github.event.repository.name }} .
    - name: Dockerhub login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Image
      run: |
        docker push zeabix/${{ github.event.repository.name }}:${{ github.sha }}